### ISSUE TITLE
 Druhý úkol mám připravený k odevzdání

### ISSUE THREAD

**Issue by Nataliia71** [Nataliia71/Ukol2#1]
@KristynaSodomkova   @pesikj  Je mi líto, ale spolu s tímto úkolem se nahrávají i další soubory (které tam byly předtím). Už jsem si s tím lámala hlavu - snažím se to řešit už dva dny, ale nejde to

**Comment by KristynaSodomkova** [comment]
Ahoj Nataliia, za me mas splneno, gratuluji :)
